module.exports = [
	/* LEVEL 1 */ ['events', 'toaster'],
	/* LEVEL 2 */ [
		'constants',
		'data',
		'dates',
		'hooks',
		'icons',
		'i18n',
		'registry',
		'rich-text-editor',
		'styles',
		'storage',
		'utils',
	],
	/* LEVEL 3 */ ['adapters', 'config', 'rrule-generator'],
	/* LEVEL 4 */ ['form', 'predicates', 'services'],
	/* LEVEL 5 */ ['components', 'edtr-services', 'helpers'],
	/* LEVEL 6 */ ['tpc'],
];
